# Generated by Django 5.1.2 on 2024-10-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectfile",
            options={"verbose_name": "Файл", "verbose_name_plural": "Файлы"},
        ),
        migrations.AlterField(
            model_name="subjectfile",
            name="file",
            field=models.FileField(
                null=True, upload_to="uploads/", verbose_name="ZIP файл"
            ),
        ),
        migrations.AlterField(
            model_name="subjectfile",
            name="subject",
            field=models.CharField(
                choices=[("phys", "Физика"), ("chem", "Химия"), ("bio", "Биология")],
                max_length=4,
                null=True,
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="subjectfile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата загрузки"
            ),
        ),
    ]
