# Generated by Django 5.1.2 on 2024-10-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_subjectfile_options_alter_subjectfile_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectfile",
            name="name",
            field=models.CharField(max_length=150, null=True, verbose_name="Название"),
        ),
    ]
