# Generated by Django 5.1.5 on 2025-02-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_subjectfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
