# Generated by Django 5.1.2 on 2024-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_subjectfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectfile",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="subjectfile",
            name="image",
            field=models.ImageField(
                null=True, upload_to="uploads/", verbose_name="Фото"
            ),
        ),
    ]
