# Generated by Django 5.1.5 on 2025-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_subjectfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfile',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
