# Generated by Django 5.1.5 on 2025-02-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_subjectfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='photo',
            field=models.ImageField(null=True, upload_to='main', verbose_name='Фото'),
        ),
    ]
