# Generated by Django 5.1.5 on 2025-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_subjectfile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
